package requests

type OrdersItem struct {
	OrderID                                      int      `json:"OrderID"`
	OrderItem                                    int      `json:"OrderItem"`
	OrderItemCategory                            string   `json:"OrderItemCategory"`
	OrderItemText                                string   `json:"OrderItemText"`
	OrderItemTextByBuyer                         string   `json:"OrderItemTextByBuyer"`
	OrderItemTextBySeller                        string   `json:"OrderItemTextBySeller"`
	Product                                      string   `json:"Product"`
	ProductStandardID                            string   `json:"ProductStandardID"`
	BaseUnit                                     string   `json:"BaseUnit"`
	StockConfirmationPartnerFunction             *string  `json:"StockConfirmationPartnerFunction"`
	StockConfirmationBusinessPartner             *int     `json:"StockConfirmationBusinessPartner"`
	StockConfirmationPlant                       *string  `json:"StockConfirmationPlant"`
	StockConfirmationPlantBatch                  *string  `json:"StockConfirmationPlantBatch"`
	StockConfirmationPlantBatchValidityStartDate *string  `json:"StockConfirmationPlantBatchValidityStartDate"`
	StockConfirmationPlantBatchValidityEndDate   *string  `json:"StockConfirmationPlantBatchValidityEndDate"`
	OrderQuantityInBaseUnit                      float32  `json:"OrderQuantityInBaseUnit"`
	OrderQuantityInIssuingUnit                   float32  `json:"OrderQuantityInIssuingUnit"`
	OrderQuantityInReceivingUnit                 float32  `json:"OrderQuantityInReceivingUnit"`
	OrderIssuingUnit                             string   `json:"OrderIssuingUnit"`
	OrderReceivingUnit                           string   `json:"OrderReceivingUnit"`
	StockConfirmationPolicy                      *string  `json:"StockConfirmationPolicy"`
	StockConfirmationStatus                      *string  `json:"StockConfirmationStatus"`
	ItemWeightUnit                               *string  `json:"ItemWeightUnit"`
	ItemGrossWeight                              *float32 `json:"ItemGrossWeight"`
	ItemNetWeight                                *float32 `json:"ItemNetWeight"`
	ProductionPlantPartnerFunction               *string  `json:"ProductionPlantPartnerFunction"`
	ProductionPlantBusinessPartner               *int     `json:"ProductionPlantBusinessPartner"`
	ProductionPlant                              *string  `json:"ProductionPlant"`
	ProductionPlantTimeZone                      *string  `json:"ProductionPlantTimeZone"`
	ProductionPlantStorageLocation               *string  `json:"ProductionPlantStorageLocation"`
	IssuingPlantPartnerFunction                  *string  `json:"IssuingPlantPartnerFunction"`
	IssuingPlantBusinessPartner                  *int     `json:"IssuingPlantBusinessPartner"`
	IssuingPlant                                 *string  `json:"IssuingPlant"`
	IssuingPlantTimeZone                         *string  `json:"IssuingPlantTimeZone"`
	IssuingPlantStorageLocation                  *string  `json:"IssuingPlantStorageLocation"`
	ReceivingPlantPartnerFunction                *string  `json:"ReceivingPlantPartnerFunction"`
	ReceivingPlantBusinessPartner                *int     `json:"ReceivingPlantBusinessPartner"`
	ReceivingPlant                               *string  `json:"ReceivingPlant"`
	ReceivingPlantTimeZone                       *string  `json:"ReceivingPlantTimeZone"`
	ReceivingPlantStorageLocation                *string  `json:"ReceivingPlantStorageLocation"`
	ProductIsBatchManagedInProductionPlant       *bool    `json:"ProductIsBatchManagedInProductionPlant"`
	ProductIsBatchManagedInIssuingPlant          *bool    `json:"ProductIsBatchManagedInIssuingPlant"`
	ProductIsBatchManagedInReceivingPlant        *bool    `json:"ProductIsBatchManagedInReceivingPlant"`
	BatchMgmtPolicyInProductionPlant             *string  `json:"BatchMgmtPolicyInProductionPlant"`
	BatchMgmtPolicyInIssuingPlant                *string  `json:"BatchMgmtPolicyInIssuingPlant"`
	BatchMgmtPolicyInReceivingPlant              *string  `json:"BatchMgmtPolicyInReceivingPlant"`
	ProductionPlantBatch                         *string  `json:"ProductionPlantBatch"`
	IssuingPlantBatch                            *string  `json:"IssuingPlantBatch"`
	ReceivingPlantBatch                          *string  `json:"ReceivingPlantBatch"`
	ProductionPlantBatchValidityStartDate        *string  `json:"ProductionPlantBatchValidityStartDate"`
	ProductionPlantBatchValidityEndDate          *string  `json:"ProductionPlantBatchValidityEndDate"`
	IssuingPlantBatchValidityStartDate           *string  `json:"IssuingPlantBatchValidityStartDate"`
	IssuingPlantBatchValidityEndDate             *string  `json:"IssuingPlantBatchValidityEndDate"`
	ReceivingPlantBatchValidityStartDate         *string  `json:"ReceivingPlantBatchValidityStartDate"`
	ReceivingPlantBatchValidityEndDate           *string  `json:"ReceivingPlantBatchValidityEndDate"`
	Incoterms                                    *string  `json:"Incoterms"`
	BPTaxClassification                          string   `json:"BPTaxClassification"`
	ProductTaxClassification                     string   `json:"ProductTaxClassification"`
	BPAccountAssignmentGroup                     string   `json:"BPAccountAssignmentGroup"`
	ProductAccountAssignmentGroup                string   `json:"ProductAccountAssignmentGroup"`
	PaymentTerms                                 string   `json:"PaymentTerms"`
	PaymentMethod                                string   `json:"PaymentMethod"`
	Project                                      *string  `json:"Project"`
	TaxCode                                      *string  `json:"TaxCode"`
	TaxRate                                      *float32 `json:"TaxRate"`
	CountryOfOrigin                              *string  `json:"CountryOfOrigin"`
}
